### PR TITLE
Followup on the workflow

### PR DESCRIPTION
**Pull request by AhmedFat7y**
I Modified some settings to better suit more people.

1. Configured prettier to work with stylelint
2. Changed indentation from spaces to tabs.
   - It works better for everyone as the size of the tab can be customized in editors (if some pople prefer 4 over 2 or viceversa)
3. Added trailing comma rule. This helps with when you to append to the list quickly, usually the comma is forgotten. Also, It won't harm anyone.

### CODE REVIEW

**Comment by AhmedFat7y** [comment]
There are still a lot of things to do (one thing is to update the README)

**Comment by ahmadalfy** [comment]
Holly shit I didn't see all these changes until now by accident. Thank you ❤️ 

Will you update the readme before I merge or you prefer to do that later? I will go through the commits and get back to you asap

**Comment by AhmedFat7y** [comment]
1. I think I will update the `README.md` later. I still need to add couple of things before doing so.
2. You need to update the README with info about the style files structure, at lease its name as the filenames are not that intuitive to reason about which goes where.
4. I was trying to use a variant of `postcss` that depends on nesting rather curly braces. On long files with 3~4 level nesting, it becomes really beneficial to remove the 5~5 curly braces after each other at the end of the rules. At that point you can increase the tab-size and debug or trace the code seamlessly. But it didn't have `prettier/stylelint` support so I reverted back for now.
5.  The variant is called [SugarSS](https://github.com/postcss/sugarss) but there was no prettier support so reverted back to postcss.

**Comment by ahmadalfy** [comment]
Merged, please update readme when you can.

**Pull request merged**
